import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, getSession } from 'next-auth/react'
import { useEffect } from "react"
import { useRouter } from 'next/router'
import SignInButton from '../components/SignInButton'
import { Grid, Typography, Container } from '@mui/material';
import { TextLoop } from "react-text-loop-next";
import LoadingPage from '../components/LoadingPage'


export default function Home() {

  const { data: session } = useSession()
  const router = useRouter()

  useEffect(() => {
    if (session) {
      router.replace('/edition')
    }
  })

  if (session) {
    return (
      <LoadingPage />
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Twrtle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomepageCopy />
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

function HomepageCopy() {

  const loop_items = ['authors', 'bloggers', 'creators', 'doers', 'influencers', 'thinkers']

  return <Container sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
    <Typography sx={{ my: 2, textAlign: 'center' }} variant="h1" component="h1">
      Consume your favourite tweets mindfully.
    </Typography>
    <Typography sx={{ my: 2, textAlign: 'center' }} variant="large" component="h2">
      Improve your Twitter signal-to-noise ratio with a weekly round-up of your favourite <TextLoop>{loop_items.map((value, index) => <span key={index}>{value}</span>)}</TextLoop>.
    </Typography>
    <SignInButton />
    <Typography sx={{ my: 2 }} variant="small" component="span">Join Andy and 100&apos;s of others developing a slower, healthier relationship with social media.</Typography>

  </Container>
}

export async function getServerSideProps(context) {
  return {
    props: {
      session: await getSession(context),
    },
  }
}
